### 유저 정보 생성
POST http://localhost:8080/api/users
Content-Type: application/json
Accept-Language: en

{
  "email": "test@gmail.com",
  "password": "1234",
  "username": "테스트"
}

### 유저 로그인

POST http://localhost:8080/api/users/authenticate
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}

### 유저 정보 찾기
GET http://localhost:8080/api/users/1
Content-Type: application/json
Cookie: JSESSIONID=8AA3C55695AEF472D07F4665E99CD745

### 전체 사용자 찾기
GET http://localhost:8080/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiO1iJ0ZXN0QGdtYWlsLmNvbSIsInVpZCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwidXNlcm5hbWUiOiLthYzsiqTtirgiLCJpYXQiOjE3Mzc1MTMzMzUsImV4cCI6MTczNzUxNTEzNX0.Ze6shJYW6hSDww2YMCFgR6i3P0SeJcMxbPsgMaUsGMk
Content-Type: application/json

###

### 페이지 정보
GET http://localhost:8080/api/users?page=1&size=5
Content-Type: application/json